#!/bin/sh

debug=
if [ $# -gt 0 ]
then
   if [ $1 = "debug" ]
   then
	debug="C_COMPILER_FLAGS=-g"
	shift
   fi
fi

if [ x$VLSI_TOOLS_SRC = x ]
then
	echo "Environment variable VLSI_TOOLS_SRC should point to the source tree"
	exit 1
else
	if [ ! -f $VLSI_TOOLS_SRC/configure ]
	then
	   echo "Environment variable VLSI_TOOLS_SRC should point to the source tree"
	   exit 1
        fi
fi

echo "Building common library/generators..." && \
   make $debug -C common install_inc && \
   make $debug -C common install && \
   make $debug -C pgen install && \
   make $debug -C miniscm install 

make $debug && echo && echo 'Run "make install" to install the binaries'
