#!/bin/sh
#-------------------------------------------------------------------------
#
#  Copyright (c) 2011, 2019 Rajit Manohar
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor,
#  Boston, MA  02110-1301, USA.
#
#-------------------------------------------------------------------------

ARCH=`$VLSI_TOOLS_SRC/scripts/getarch`
OS=`$VLSI_TOOLS_SRC/scripts/getos`

EXT=${ARCH}_${OS}

#
# Move .o and .so files into current directory from build sub-directory
#

if [ ! -d $EXT ]
then 
	mkdir $EXT
fi

objs=`echo $EXT/*.o`
if [ "$objs" = $EXT/\*.o ]
then
	:
else
	mv -f $EXT/*.o . 
fi

objs=`echo $EXT/*.os`
if [ "$objs" = $EXT/\*.os ]
then
	:
else
	mv -f $EXT/*.os .
fi
