#-------------------------------------------------------------------------
#
#  Copyright (c) 2011-2018 Rajit Manohar
#  All Rights Reserved
#
#-------------------------------------------------------------------------
#
# Make everything, in the right order
# 
SUBDIRS=prsim tlint

include $(VLSI_TOOLS_SRC)/scripts/Makefile.std
