#-------------------------------------------------------------------------
#
#  Copyright (c) 2018 Rajit Manohar
#  All Rights Reserved
#
#-------------------------------------------------------------------------

weird: install_inc all

EXTRA=aflat.o flatten.o
TARGETINCS=aflat.h
TARGETINCSUBDIR=act/passes

SRCS=$(EXTRA:.o=.cc)

include $(VLSI_TOOLS_SRC)/scripts/Makefile.std

-include Makefile.deps
