#!/bin/sh
#-------------------------------------------------------------------------
#
#  Copyright (c) 2021 Rajit Manohar
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor,
#  Boston, MA  02110-1301, USA.
#
#-------------------------------------------------------------------------

#
#
# Basic install script for scripts/: copy file over if it changes,
# and replace VLSI_TOOLS_SRC with ACT_HOME
#
#

if [ $# -ne 0 ]
then
        echo "Usage: `basename $0`"
        exit 1
fi

for i in install config Makefile.std getarch getbaseos getos move-in move-out mymakedepend linkso findpkg tconfig
do
    sed 's/VLSI_TOOLS_SRC/ACT_HOME/g' < $i > tmpfile
    src=tmpfile
    dest=$ACT_HOME/scripts/$i

    if [ -r $src ]
    then
	if cmp -s $src $dest
	then
            : # echo "[Unchanged $src]"
	else
            if [ -f $dest ]
            then
                mv $dest ${dest}.old
            fi
            echo "[Installing $i]"
            cp $src $dest
	fi
    else
	echo "$i is unreadable"
    fi
    rm -f tmpfile
done

for i in install getarch getos getbaseos move-in move-out mymakedepend linkso findpkg tconfig
do
    chmod +x $ACT_HOME/scripts/$i
done
