#!/bin/sh
#-------------------------------------------------------------------------
#
#  Copyright (c) 2011, 2019 Rajit Manohar
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor,
#  Boston, MA  02110-1301, USA.
#
#-------------------------------------------------------------------------

#
#
# Basic install script: copy file over if it changes
#
#

if [ $# -ne 2 ]
then
        echo "Usage: `basename $0` source dest"
        exit 1
fi

src=$1
dest=$2

if [ -r $src ]
then
   if cmp -s $src $dest
   then
        echo "[Unchanged $src]"
   else
        if [ -f $dest ]
        then
                mv $dest ${dest}.old
        fi
        echo "[Installing $src]"
        cp $src $dest
   fi
else
   echo "$src is unreadable"
fi
