#!/bin/sh

. $VLSI_TOOLS_SRC/scripts/config

lib=$1
shift

if [ $BASEOS = "darwin" ]
then
	$CXX_COMPILER_NAME $SH_LINK_OPTIONS -o $lib "$@" -install_name $ACT_HOME/lib/$lib
else
	$CXX_COMPILER_NAME $SH_LINK_OPTIONS -o $lib "$@"
fi
