#!/bin/sh
#-------------------------------------------------------------------------
#
#  Copyright (c) 2011 Rajit Manohar
#  All Rights Reserved
#
#-------------------------------------------------------------------------

ARCH=`$VLSI_TOOLS_SRC/scripts/getarch`
OS=`$VLSI_TOOLS_SRC/scripts/getos`

EXT=${ARCH}_${OS}

#
# Move .o and .so files into current directory from build sub-directory
#

if [ ! -d $EXT ]
then 
	mkdir $EXT
fi

objs=`echo $EXT/*.o`
if [ "$objs" = $EXT/\*.o ]
then
	:
else
	mv -f $EXT/*.o . 
fi

objs=`echo $EXT/*.os`
if [ "$objs" = $EXT/\*.os ]
then
	:
else
	mv -f $EXT/*.os .
fi
