#!/bin/sh
#-------------------------------------------------------------------------
#
#  Copyright (c) 2011 Rajit Manohar
#  All Rights Reserved
#
#-------------------------------------------------------------------------

#
# Script that replaces makedepend, which has bugs on some platforms.
#

LINE="# DO NOT DELETE THIS LINE -- make depend depends on it."

srcs=$1
shift

echo $LINE > Makefile.deps

if [ "x$srcs" = "x" ]
then
        :
else
    for i in $srcs
    do 
      s=`expr $i : '.*\(.cc\)'`
      if [ "x$s" = "x.cc" ]
      then
          g++ -MM $@ $i >> Makefile.deps
      else
	  gcc -MM $@ $i >> Makefile.deps
      fi
    done
fi
