#!/bin/sh
#-------------------------------------------------------------------------
#
#  Copyright (c) 2011 Rajit Manohar
#  All Rights Reserved
#
#-------------------------------------------------------------------------

#
# Script that replaces makedepend, which has bugs on some platforms.
#

LINE="# DO NOT DELETE THIS LINE -- make depend depends on it."

srcs=$1
shift

echo $LINE > Makefile.deps

if [ "x$srcs" = "x" ]
then
        :
else
        g++ -MM $@ $srcs >> Makefile.deps
fi
