#!/bin/sh
#-------------------------------------------------------------------------
#
#  Copyright (c) 2011, 2019 Rajit Manohar
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor,
#  Boston, MA  02110-1301, USA.
#
#-------------------------------------------------------------------------


#
# Script that replaces makedepend, which has bugs on some platforms.
#

LINE="# DO NOT DELETE THIS LINE -- make depend depends on it."

srcs=$1
shift

echo $LINE > Makefile.deps

if [ "x$srcs" = "x" ]
then
        :
else
    for i in $srcs
    do 
      s=`expr $i : '.*\(.cc\)'`
      if [ "x$s" = "x.cc" ]
      then
          g++ -MM $@ $i >> Makefile.deps
      else
	  gcc -MM $@ $i >> Makefile.deps
      fi
    done
fi
